# circleci/config.yml

version: 2.1
orbs:
  # This Orb includes the following:
  # - checkout current repository
  # - npm install with caching
  # - start the server
  # - wait for the server to respond
  # - run Cypress tests
  # - store videos and screenshots as artifacts on CircleCI
  cypress: cypress-io/cypress@1

jobs:
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - restore_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run: npm ci
      - save_cache:
          key: myapp-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: npm run build
      - persist_to_workspace:
          root: ~/myapp
          paths:
            - docs/*
  deploy:
    working_directory: ~/myapp
    docker:
      - image: node:8.10.0
    steps:
      - add_ssh_keys:
          fingerprints:
            - "65:fa:3b:52:53:9b:19:28:29:fa:77:0b:79:18:e5:bc"
      - checkout
      - attach_workspace:
          at: ~/myapp
      - run:
          name: Install gh-pages
          command: |
            npm install -g --silent gh-pages
      - run:
          name: Configure git
          command: |
            git config user.email "gregor.biswanger@web-enliven.de"
            git config user.name "GregorBiswanger"
      - run:
          name: Deploy to gh-pages branch
          command: gh-pages --message "[ci skip]" -d docs

workflows:
  test-build-deploy:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: "http://localhost:4200"
          store_artifacts: true
      - build:
          requires:
            - cypress/run
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
